version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENV=production
    env_file:
      - .env
    command: ["uvicorn", "backend.src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=production
    command: [ "npm", "run", "dev", "--", "--host" ]

networks:
  default:
    driver: bridge
